name: permission_handler_android_pro
description: Permission plugin for Flutter (Pro version by SiTechra (Pvt) Ltd). This plugin provides the Android API to request and check permissions.
homepage: https://pub.dev/packages/permission_handler_pro
version: 13.0.1

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

flutter:
  plugin:
    implements: permission_handler_pro
    platforms:
      android:
        package: com.baseflow.permissionhandler
        pluginClass: PermissionHandlerPlugin

dependencies:
  flutter:
    sdk: flutter
  permission_handler_platform_interface_pro:
    path: ../permission_handler_platform_interface

dev_dependencies:
  flutter_lints: ^5.0.0
  plugin_platform_interface: ^2.0.0
