name: permission_handler_apple_pro
description: Permission plugin for Flutter (Pro version by SiTechra (Pvt) Ltd). This plugin provides the iOS API to request and check permissions.
homepage: https://pub.dev/packages/permission_handler_pro
version: 9.4.9

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

flutter:
  plugin:
    implements: permission_handler_pro
    platforms:
      ios:
        pluginClass: PermissionHandlerPlugin

dependencies:
  flutter:
    sdk: flutter
  permission_handler_platform_interface_pro: ^4.3.0

dev_dependencies:
  flutter_lints: ^1.0.4
  plugin_platform_interface: ^2.0.0

dependency_overrides:
  permission_handler_platform_interface_pro:
    path: ../permission_handler_platform_interface
