name: permission_handler_html_pro
description: Permission plugin for Flutter (Pro version by SiTechra (Pvt) Ltd). This plugin provides the web API to request and check permissions.
version: 0.1.3+5

homepage: https://pub.dev/packages/permission_handler_pro

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  permission_handler_platform_interface_pro: ^4.3.0
  web: ">=0.5.1 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.2
  build_runner: ^2.1.2
  test: ^1.24.4

flutter:
  plugin:
    implements: permission_handler_pro
    platforms:
      web:
        pluginClass: WebPermissionHandler
        fileName: permission_handler_html_pro.dart

dependency_overrides:
  permission_handler_platform_interface_pro:
    path: ../permission_handler_platform_interface
