name: permission_handler_pro
description: Permission plugin for Flutter (Pro version by SiTechra (Pvt) Ltd). This plugin provides a cross-platform (iOS, Android) API to request and check permissions.
homepage: https://pub.dev/packages/permission_handler_pro
version: 12.0.3

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: permission_handler_android_pro
      ios:
        default_package: permission_handler_apple_pro
      web:
        default_package: permission_handler_html_pro
      windows:
        default_package: permission_handler_windows_pro

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0
  permission_handler_android_pro: ^13.0.1
  permission_handler_apple_pro: ^9.4.9
  permission_handler_html_pro: ^0.1.3+5
  permission_handler_windows_pro: ^0.2.1
  permission_handler_platform_interface_pro: ^4.3.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5
  plugin_platform_interface: ^2.0.0

dependency_overrides:
  permission_handler_android_pro:
    path: ../permission_handler_android
  permission_handler_apple_pro:
    path: ../permission_handler_apple
  permission_handler_html_pro:
    path: ../permission_handler_html
  permission_handler_windows_pro:
    path: ../permission_handler_windows
  permission_handler_platform_interface_pro:
    path: ../permission_handler_platform_interface
